# Generated by Django 2.1.7 on 2019-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0003_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=240)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cartao', models.IntegerField()),
                ('pagamento', models.CharField(choices=[('P2', 'Pagamento parcelado 2x'), ('P3', 'Pagamento parcelado 3x'), ('P4', 'Pagamento parcelado 4x')], default='PV', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
